Repository weni-ai/nexus-ai, pull requests merged in 2025-09, with the labels that each got.

#742 Change multi agent permission
  nexus/inline_agents/api/views.py
Labels: Review effort 2/5, Possible security concern

#747 Feature/OpenAI traces hooks
  inline_agents/backends/openai/adapter.py
  inline_agents/backends/openai/backend.py
  inline_agents/backends/openai/hooks.py
  inline_agents/backends/openai/sessions.py
  inline_agents/backends/openai/tools.py
Labels: Review effort 4/5, Possible security concern

#746 fix: adds cache for keycloak token
  nexus/cache/__init__.py
  nexus/cache/token.py
  nexus/internals/__init__.py
  nexus/usecases/inline_agents/typing.py
Labels: Review effort 2/5, Possible security concern

#749 Fix empty msgs
  router/clients/flows/http/send_message.py
Labels: Review effort 2/5

#777 update litellm to 1.76.3
  poetry.lock
  pyproject.toml
Labels: Review effort 1/5

#778 Feature/save OpenAI traces s3
  inline_agents/backends/openai/hooks.py
Labels: Review effort 2/5

#779 Integrate Langfuse client for tracing in OpenAI backend, enhancing ev…
  inline_agents/backends/openai/backend.py
  poetry.lock
  pyproject.toml
Labels: Review effort 2/5, Possible security concern

#781 Add foundation models to Agent and Project models, update related fun…
  inline_agents/backends/openai/adapter.py
  nexus/inline_agents/admin.py
  nexus/inline_agents/migrations/0012_agent_backend_foundation_models.py
  nexus/inline_agents/models.py
  nexus/inline_agents/team/repository.py
  nexus/inline_agents/team/test_repository.py
  nexus/projects/migrations/0019_project_default_collaborators_foundation_model.py
  nexus/projects/models.py
  nexus/settings.py
  nexus/usecases/inline_agents/create.py
  nexus/usecases/inline_agents/tests/test_usecases.py
Labels: Review effort 3/5

#783 Fix/enhance collaborators foundation model
  nexus/inline_agents/models.py
  nexus/inline_agents/team/repository.py
  nexus/inline_agents/team/test_repository.py
  nexus/projects/admin.py
  router/tasks/invoke.py
Labels: Review effort 3/5

#787 Fix/session limit items
  inline_agents/backends/openai/backend.py
  inline_agents/backends/openai/sessions.py
Labels: Review effort 2/5

#775 Add new intelligence router validation
  nexus/intelligences/migrations/0026_intelligence_is_router.py
  nexus/intelligences/models.py
  nexus/usecases/intelligences/create.py
  nexus/usecases/intelligences/get_by_uuid.py
  nexus/usecases/projects/projects_use_case.py
Labels: Review effort 2/5

#789 send foundation model and backend in data lake event metadata
  inline_agents/backends/bedrock/adapter.py
  inline_agents/backends/bedrock/backend.py
  inline_agents/backends/openai/adapter.py
  inline_agents/backends/openai/hooks.py
Labels: Review effort 2/5

#790 Update foundation model retrieval in ProjectsUseCase to use current_f…
  nexus/usecases/projects/projects_use_case.py
Labels: Review effort 2/5

#795 Enhance event handling in CollaboratorHooks and SupervisorHooks to en…
  inline_agents/backends/openai/hooks.py
Labels: Review effort 2/5
