Repository weni-ai/nexus-ai, pull requests merged in 2025-07, with the labels that each got.

#622 new mailroom fields
  inline_agents/backends/bedrock/adapter.py
  inline_agents/backends/bedrock/backend.py
  router/entities/mailroom.py
  router/http_bodies.py
  router/tasks/invoke.py
Labels: Review effort 2/5

#629 Add empty msg error
  router/tasks/exceptions.py
  router/tasks/invoke.py
Labels: Review effort 3/5, Possible security concern

#634 Feature/send events to datalake
  inline_agents/backends/bedrock/adapter.py
  inline_agents/backends/bedrock/backend.py
Labels: Review effort 3/5, Possible security concern

#635 adding check if is a dict the action group data text
  inline_agents/backends/bedrock/adapter.py
  inline_agents/backends/bedrock/backend.py
Labels: Review effort 2/5

#637 Update boto3 and add project prompt creation configurations
  inline_agents/backends/bedrock/backend.py
  nexus/projects/api/routers.py
  nexus/projects/api/views.py
  nexus/projects/migrations/0015_project_conversation_turns_to_include_and_more.py
  nexus/projects/models.py
  nexus/projects/tests/test_models.py
  nexus/usecases/projects/projects_use_case.py
  poetry.lock
  pyproject.toml
  router/tasks/invoke.py
Labels: Review effort 3/5

#652 adding start date and end date and the migration
  nexus/intelligences/consumers/conversation_consumer.py
  nexus/intelligences/models.py
  nexus/usecases/inline_agents/create.py
  nexus/usecases/intelligences/lambda_usecase.py
Labels: Review effort 2/5

#672 Feauture: Unittests datalake
  inline_agents/backends/bedrock/adapter.py
  inline_agents/backends/bedrock/backend.py
  inline_agents/backends/bedrock/tests/test_adapter.py
  inline_agents/backends/bedrock/tests/traces_factory.py
Labels: Review effort 3/5, Possible security concern

#676 Feature/call lambda functions
  nexus/usecases/intelligences/lambda_usecase.py
Labels: Review effort 2/5

#681 call topic lambda function
  nexus/celery.py
  nexus/inline_agents/handle.py
  nexus/intelligences/consumers/conversation_consumer.py
  nexus/usecases/inline_agents/create.py
  nexus/usecases/intelligences/lambda_usecase.py
Labels: Review effort 3/5

#687 Update file upload function to include file name
  nexus/task_managers/tasks.py
Labels: Review effort 2/5

#689 Add channel parameter to session attributes
  inline_agents/backends/bedrock/adapter.py
Labels: Review effort 2/5

#693 Fix line endings in instruction replacement for BedrockTeamAdapter
  inline_agents/backends/bedrock/adapter.py
Labels: Review effort 2/5

#694 Add channel UUID to contact information in BedrockTeamAdapter
  inline_agents/backends/bedrock/adapter.py
Labels: Review effort 2/5

#696 conversation create when a agent are invoke and update her when close…
  inline_agents/backends/bedrock/backend.py
  nexus/usecases/inline_agents/update.py
  nexus/usecases/intelligences/lambda_usecase.py
Labels: Review effort 4/5

#697 send the agent_uuid when the event data is weni csat or nps
  inline_agents/backends/bedrock/adapter.py
  nexus/settings.py
Labels: Review effort 2/5

#690 send the agent_uuid when the event data is weni csat or nps
  inline_agents/backends/bedrock/adapter.py
  nexus/settings.py
Labels: Review effort 2/5
