Repository weni-ai/nexus-ai, pull requests merged in 2025-08, with the labels that each got.

#701 Remove filter by channel on typing
  inline_agents/backends/bedrock/backend.py
  nexus/usecases/inline_agents/typing.py
  router/tasks/invoke.py
Labels: Review effort 2/5

#702 Update Project model to set default for use_prompt_creation_configura…
  nexus/inline_agents/api/views.py
  nexus/projects/migrations/0016_alter_project_use_prompt_creation_configurations.py
  nexus/projects/models.py
Labels: Review effort 2/5

#695 Implement OpenAI backend integration and session management
  inline_agents/backends/__init__.py
  inline_agents/backends/openai/adapter.py
  inline_agents/backends/openai/backend.py
  inline_agents/backends/openai/entities.py
  inline_agents/backends/openai/hooks.py
  inline_agents/backends/openai/sessions.py
  inline_agents/backends/openai/tools.py
  nexus/inline_agents/admin.py
  nexus/inline_agents/backends/openai/models.py
  nexus/inline_agents/migrations/0006_openaisupervisor.py
  nexus/projects/api/routers.py
  nexus/projects/api/views.py
  nexus/settings.py
  nexus/usecases/projects/projects_use_case.py
  nexus/usecases/projects/tests/test_agents_backend.py
  poetry.lock
  pyproject.toml
Labels: Review effort 4/5, Possible security concern

#704 Enhance Bedrock and OpenAI adapters with additional parameters and qu…
  inline_agents/backends/bedrock/adapter.py
  inline_agents/backends/bedrock/backend.py
  inline_agents/backends/openai/adapter.py
  inline_agents/backends/openai/backend.py
  nexus/usecases/intelligences/get_by_uuid.py
  router/tasks/invoke.py
Labels: Review effort 3/5

#707 Feature: Update conversation on csat/nps
  inline_agents/backends/bedrock/adapter.py
  inline_agents/backends/bedrock/backend.py
  inline_agents/backends/bedrock/tests/test_adapter.py
  inline_agents/backends/bedrock/tests/traces_factory.py
  nexus/intelligences/models.py
  nexus/usecases/intelligences/lambda_usecase.py
  nexus/usecases/intelligences/tests/intelligence_factory.py
Labels: Review effort 3/5

#670 Feature: New inline content base file endpoint
  nexus/intelligences/api/routers.py
  nexus/intelligences/api/views.py
  nexus/task_managers/file_manager/celery_file_manager.py
  nexus/task_managers/tasks.py
  nexus/task_managers/tasks_bedrock.py
  nexus/usecases/intelligences/list.py
  nexus/usecases/intelligences/retrieve.py
  nexus/usecases/intelligences/update.py
Labels: Review effort 4/5

#708 Merge migrations
  nexus/inline_agents/migrations/0007_merge_20250813_2118.py
Labels: Review effort 1/5

#712 Improve debug tags and filters
  router/tasks/invoke.py
  router/traces_observers/save_traces.py
Labels: Review effort 2/5, Possible security concern

#713 Fix/OpenAI backend
  inline_agents/backends/openai/adapter.py
  inline_agents/backends/openai/tools.py
Labels: Review effort 2/5

#714 Refactor guardrail handling in Project model to enhance functionality…
  nexus/projects/migrations/0018_alter_project_guardrail.py
Labels: Review effort 2/5

#718 Feature: Add agent uuid on metadata
  inline_agents/backends/bedrock/adapter.py
  inline_agents/backends/bedrock/backend.py
  nexus/usecases/inline_agents/update.py
Labels: Review effort 2/5

#720 Fix resolution mapping
  nexus/usecases/intelligences/lambda_usecase.py
  router/tasks/invoke.py
Labels: Review effort 2/5, Possible security concern

#722 Add event processing and logging for OpenAI backend
  inline_agents/backends/openai/adapter.py
  inline_agents/backends/openai/backend.py
  nexus/event_domain/event_manager.py
  nexus/events.py
  nexus/projects/websockets/consumers.py
  router/traces_observers/summary.py
Labels: Review effort 3/5

#726 Refactor BedrockSupervisorRepository to streamline foundation model r…
  inline_agents/backends/bedrock/backend.py
  nexus/inline_agents/backends/bedrock/repository.py
  nexus/inline_agents/backends/bedrock/tests.py
  nexus/settings.py
Labels: Review effort 2/5

#731 Updated create_function_args_class to set default values for optional…
  inline_agents/backends/openai/adapter.py
  inline_agents/backends/openai/tests/test_adapter.py
Labels: Review effort 2/5

#733 Fix: Corrected contact_urn assignment in OpenAIBackend
  inline_agents/backends/openai/backend.py
Labels: Review effort 1/5, Possible security concern

#732 Remove foundation model assignment from UpdateAgentUseCase
  nexus/usecases/inline_agents/update.py
Labels: Review effort 1/5

#736 Refactor: Rearrange imports and enhance session ID handling in Bedroc…
  inline_agents/backends/bedrock/adapter.py
  inline_agents/backends/bedrock/tests/test_adapter.py
Labels: Review effort 2/5

#735 Feature: Refactor supervisor endpoint
  nexus/intelligences/api/filters.py
  nexus/intelligences/api/serializers.py
  nexus/intelligences/api/tests/mocks.py
  nexus/intelligences/api/tests/test_views.py
  nexus/intelligences/api/views.py
  nexus/internals/billing.py
  nexus/usecases/intelligences/supervisor.py
  nexus/usecases/intelligences/tests/intelligence_factory.py
Labels: Review effort 3/5

#738 Enhancement: Introduce agent proxy tool and session management improv…
  inline_agents/backends/openai/adapter.py
  inline_agents/backends/openai/backend.py
  inline_agents/backends/openai/entities.py
  inline_agents/backends/openai/hooks.py
  inline_agents/backends/openai/sessions.py
Labels: Review effort 3/5

#741 fix external id
  nexus/usecases/intelligences/lambda_usecase.py
Labels: Review effort 2/5

#744 fix lambda compononents
  inline_agents/backends/bedrock/backend.py
Labels: Review effort 1/5
