Repository weni-ai/nexus-ai, pull requests merged in 2025-10, with the labels that each got.

#800 Enhance WeniGPTClient to support Bedrock conversation with custom mod…
  nexus/intelligences/llms/chatgpt.py
  nexus/intelligences/llms/client.py
  nexus/intelligences/llms/wenigpt.py
  nexus/settings.py
  router/llms/call.py
  router/route.py
Labels: Review effort 3/5

#802 Fix IntegratedIntelligence multiple objects
  nexus/usecases/intelligences/get_by_uuid.py
Labels: Review effort 1/5

#803 Feature/OpenAI components
  inline_agents/backends/openai/adapter.py
  inline_agents/backends/openai/backend.py
  inline_agents/backends/openai/components_tools.py
  inline_agents/backends/openai/entities.py
  inline_agents/backends/openai/hooks.py
  inline_agents/backends/openai/tools.py
  nexus/inline_agents/admin.py
  nexus/inline_agents/backends/openai/models.py
  nexus/inline_agents/backends/openai/repository.py
Labels: Review effort 4/5
