Repository weni-ai/nexus-ai, pull requests merged in 2025-04, with the labels that each got.

#509 Feature/inline agents adapter
  inline_agents/backends/bedrock/adapter.py
  inline_agents/backends/bedrock/backend.py
  inline_agents/backends/tests/inline_factories.py
  inline_agents/backends/tests/test_adapter.py
  inline_agents/team/repository.py
  nexus/inline_agents/backends/__init__.py
  nexus/inline_agents/backends/bedrock/__init__.py
  nexus/inline_agents/backends/bedrock/models.py
  nexus/inline_agents/backends/bedrock/repository.py
  nexus/inline_agents/backends/bedrock/tests.py
  nexus/inline_agents/backends/openai/__init__.py
  nexus/inline_agents/migrations/0002_supervisor.py
  nexus/inline_agents/team/exceptions.py
  nexus/inline_agents/team/repository.py
  nexus/settings.py
Labels: Review effort 3/5

#506 Feature: Observers base
  nexus/events.py
  router/tasks/observer.py
Labels: Review effort 2/5

#510 Feature: Update traces endpoint to inline_traces
  nexus/agents/api/views.py
  nexus/agents/models.py
  nexus/logs/api/serializers.py
  nexus/logs/api/views.py
  nexus/task_managers/file_database/bedrock.py
  nexus/usecases/agents/agents.py
  nexus/usecases/logs/list.py
  router/traces_observers/save_traces.py
Labels: Review effort 2/5

#511 Fix: Human support null
  nexus/intelligences/api/serializers.py
Labels: Review effort 4/5

#512 Add a handler to attachments
  router/tasks/invoke.py
Labels: Review effort 2/5

#505 Feature/inline agents components
  nexus/agents/api/routers.py
  nexus/inline_agents/api/views.py
  nexus/inline_agents/components.py
  nexus/projects/models.py
  nexus/usecases/inline_agents/create.py
  nexus/usecases/inline_agents/instructions.py
  nexus/usecases/inline_agents/update.py
Labels: Review effort 3/5

#508 Add missing knowledge-base
  inline_agents/backends/bedrock/backend.py
  router/tasks/invoke.py
Labels: Review effort 2/5

#519 Fix: rationale validation
  router/traces_observers/rationale_observer.py
Labels: Review effort 2/5

#523 Temp fix: Turn off supervisor on specific project
  nexus/logs/api/views.py
Labels: Review effort 2/5

#524 Add rationale handling to BedrockBackend
  inline_agents/backends/bedrock/backend.py
  inline_agents/backends/tests/test_adapter.py
Labels: Review effort 2/5

#525 Fix: Disable supervisor endpoint
  nexus/logs/api/views.py
Labels: Review effort 2/5

#522 Add LogGroup API and corresponding use case
  nexus/agents/api/routers.py
  nexus/inline_agents/api/views.py
  nexus/inline_agents/tests.py
  nexus/usecases/inline_agents/bedrock.py
  nexus/usecases/inline_agents/get.py
Labels: Review effort 2/5
